import dataclasses

@dataclasses.dataclass(frozen=True, slots=True)
class TelemetryPacket:
    """
    Forza Horizon Telemetry Packet (Data Out format).
    """
    is_race_on: int
    timestamp_ms: int
    engine_max_rpm: float
    engine_idle_rpm: float
    current_engine_rpm: float
    acceleration_x: float
    acceleration_y: float
    acceleration_z: float
    velocity_x: float
    velocity_y: float
    velocity_z: float
    angular_velocity_x: float
    angular_velocity_y: float
    angular_velocity_z: float
    yaw: float
    pitch: float
    roll: float
    normalized_suspension_travel_fl: float
    normalized_suspension_travel_fr: float
    normalized_suspension_travel_rl: float
    normalized_suspension_travel_rr: float
    tire_slip_ratio_fl: float
    tire_slip_ratio_fr: float
    tire_slip_ratio_rl: float
    tire_slip_ratio_rr: float
    wheel_rotation_speed_fl: float
    wheel_rotation_speed_fr: float
    wheel_rotation_speed_rl: float
    wheel_rotation_speed_rr: float
    wheel_on_rumble_strip_fl: int
    wheel_on_rumble_strip_fr: int
    wheel_on_rumble_strip_rl: int
    wheel_on_rumble_strip_rr: int
    wheel_in_puddle_depth_fl: float
    wheel_in_puddle_depth_fr: float
    wheel_in_puddle_depth_rl: float
    wheel_in_puddle_depth_rr: float
    surface_rumble_fl: float
    surface_rumble_fr: float
    surface_rumble_rl: float
    surface_rumble_rr: float
    tire_slip_angle_fl: float
    tire_slip_angle_fr: float
    tire_slip_angle_rl: float
    tire_slip_angle_rr: float
    tire_combined_slip_fl: float
    tire_combined_slip_fr: float
    tire_combined_slip_rl: float
    tire_combined_slip_rr: float
    suspension_travel_meters_fl: float
    suspension_travel_meters_fr: float
    suspension_travel_meters_rl: float
    suspension_travel_meters_rr: float
    car_ordinal: int
    car_class: int
    car_performance_index: int
    drivetrain_type: int
    num_cylinders: int
    position_x: float
    position_y: float
    position_z: float
    speed: float
    power: float
    torque: float
    tire_temp_fl: float
    tire_temp_fr: float
    tire_temp_rl: float
    tire_temp_rr: float
    boost: float
    fuel: float
    distance_traveled: float
    best_lap: float
    last_lap: float
    current_lap: float
    current_race_time: float
    lap_number: int
    race_position: int
    accel: int
    brake: int
    clutch: int
    handbrake: int
    gear: int
    steer: int
    normalized_driving_line: int
    normalized_ai_brake_difference: int
    session_id: int | None = None
